version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.school-frontend.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.school-frontend.entrypoints=websecure"
        - "traefik.http.routers.school-frontend.tls=true"
        - "traefik.http.services.school-frontend.loadbalancer.server.port=80"
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${POSTGRES_DB}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - N8N_AUTH_TOKEN=${N8N_AUTH_TOKEN}
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.school-backend.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
        - "traefik.http.routers.school-backend.entrypoints=websecure"
        - "traefik.http.routers.school-backend.tls=true"
        - "traefik.http.services.school-backend.loadbalancer.server.port=3000"
    depends_on:
      - db

  db:
    build: 
      context: ./database
      args:
        - DB_USER=${POSTGRES_USER}
        - DB_PASSWORD=${POSTGRES_PASSWORD}
        - DB_NAME=${POSTGRES_DB}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: